version: 2

sources:
  - name: production_adventure_works
    tables:
      - name: product
        columns: 
          - name: productid
            tests:
              - unique
              - not_null
      - name: productsubcategory
        columns: 
          - name: productsubcategoryid
            tests:
              - unique
              - not_null
      - name: productcategory
        columns: 
          - name: productcategoryid
            tests:
              - unique
              - not_null           
  - name: sales_adventure_works 
    tables:
      - name: salesperson
        columns: 
          - name: businessentityid
            tests:
              - unique
              - not_null
      - name: customer
        columns: 
          - name: customerid
            tests:
              - unique
              - not_null
      - name: creditcard
        columns: 
          - name: creditcardid
            tests:
              - unique
              - not_null
      - name: salesorderheader 
        columns: 
          - name: salesorderid
            tests:
              - unique
              - not_null
      - name: salesorderdetail 
        columns: 
          - name: salesorderdetailid
            tests:
              - unique
              - not_null
      - name: salesreason 
        columns: 
          - name: salesreasonid
            tests:
              - unique
              - not_null
      - name: salesorderheadersalesreason 
        columns: 
          - name: salesorderid
            tests:
              - not_null
          - name: salesreasonid
            tests:
              - not_null
      - name: salesterritory 
        columns: 
          - name: territoryid
            tests:
              - unique
              - not_null
  - name: person_adventure_works 
    tables:
      - name: person
        columns: 
          - name: businessentityid
            tests:
              - unique
              - not_null
      - name: address
        columns: 
          - name: addressid
            tests:
              - unique
              - not_null 
      - name: stateprovince
        columns: 
          - name: stateprovinceid
            tests:
              - unique
              - not_null
      - name: countryregion
        columns: 
          - name: countryregioncode
            tests:
              - unique
              - not_null   
  - name: humanresources_adventure_works 
    tables:
      - name: employee
        columns: 
          - name: businessentityid
            tests:
              - unique
              - not_null
  - name: purchasing_adventure_works 
    tables:
      - name: purchaseorderdetail
        columns: 
          - name: purchaseorderdetailid
            tests:
              - unique
              - not_null
      - name: purchaseorderheader
        columns: 
          - name: purchaseorderid
            tests:
              - unique
              - not_null